dict_sample = {'Pickens': ('354xx', 'Pickens', 'AL'),
 'Sumter': ('335xx', 'Sumter', 'FL'),
 'Jefferson': ('323xx', 'Jefferson', 'FL'),
 'Choctaw': ('369xx', 'Choctaw', 'AL'),
 'Franklin': ('305xx', 'Franklin', 'GA'),
 'Monroe': ('330xx', 'Monroe', 'FL'),
 'DeKalb': ('300xx', 'DeKalb', 'GA'),
 'Escambia': ('325xx', 'Escambia', 'FL'),
 'Lamar': ('302xx', 'Lamar', 'GA'),
 'Randolph': ('398xx', 'Randolph', 'GA'),
 'Lawrence': ('725xx', 'Lawrence', 'AR'),
 'Lee': ('339xx', 'Lee', 'FL'),
 'Marion': ('310xx', 'Marion', 'GA'),
 'Butler': ('364xx', 'Butler', 'AL'),
 'Mobile': ('365xx', 'Mobile', 'AL'),
 'Jackson': ('324xx', 'Jackson', 'FL'),
 'Talladega': ('350xx', 'Talladega', 'AL'),
 'Perry': ('721xx', 'Perry', 'AR'),
 'Walker': ('355xx', 'Walker', 'AL'),
 'Cleburne': ('725xx', 'Cleburne', 'AR'),
 'Conecuh': ('364xx', 'Conecuh', 'AL'),
 'Greene': ('724xx', 'Greene', 'AR'),
 'Barbour': ('360xx', 'Barbour', 'AL'),
 'Bibb': ('312xx', 'Bibb', 'GA'),
 'Bullock': ('360xx', 'Bullock', 'AL'),
 'Calhoun': ('398xx', 'Calhoun', 'GA'),
 'Chambers': ('368xx', 'Chambers', 'AL'),
 'Clarke': ('306xx', 'Clarke', 'GA'),
 'Fayette': ('355xx', 'Fayette', 'AL'),
 'Montgomery': ('304xx', 'Montgomery', 'GA'),
 'Marshall': ('357xx', 'Marshall', 'AL'),
 'Blount': ('350xx', 'Blount', 'AL'),
 'Henry': ('302xx', 'Henry', 'GA'),
 'Madison': ('306xx', 'Madison', 'GA'),
 'Tuscaloosa': ('354xx', 'Tuscaloosa', 'AL'),
 'Washington': ('324xx', 'Washington', 'FL'),
 'Clay': ('398xx', 'Clay', 'GA'),
 'Coffee': ('363xx', 'Coffee', 'AL'),
 'Morgan': ('306xx', 'Morgan', 'GA'),
 'Pike': ('719xx', 'Pike', 'AR'),
 'Chilton': ('351xx', 'Chilton', 'AL'),
 'Colbert': ('356xx', 'Colbert', 'AL'),
 'Coosa': ('360xx', 'Coosa', 'AL'),
 'Dale': ('363xx', 'Dale', 'AL'),
 'Hale': ('367xx', 'Hale', 'AL'),
 'Etowah': ('359xx', 'Etowah', 'AL'),
 'Autauga': ('360xx', 'Autauga', 'AL'),
 'Tallapoosa': ('368xx', 'Tallapoosa', 'AL'),
 'Geneva': ('363xx', 'Geneva', 'AL'),
 'Wilcox': ('310xx', 'Wilcox', 'GA'),
 'Marengo': ('367xx', 'Marengo', 'AL'),
 'Russell': ('368xx', 'Russell', 'AL'),
 'Cherokee': ('359xx', 'Cherokee', 'AL'),
 'Covington': ('364xx', 'Covington', 'AL'),
 'Crenshaw': ('360xx', 'Crenshaw', 'AL'),
 'Dallas': ('717xx', 'Dallas', 'AR'),
 'Lauderdale': ('356xx', 'Lauderdale', 'AL'),
 'Lowndes': ('360xx', 'Lowndes', 'AL'),
 'Macon': ('310xx', 'Macon', 'GA'),
 'Limestone': ('357xx', 'Limestone', 'AL'),
 'Shelby': ('351xx', 'Shelby', 'AL'),
 'Saint Clair': ('359xx', 'Saint Clair', 'AL'),
 'Winston': ('355xx', 'Winston', 'AL'),
 'Baldwin': ('310xx', 'Baldwin', 'GA'),
 'Cullman': ('350xx', 'Cullman', 'AL'),
 'Elmore': ('360xx', 'Elmore', 'AL'),
 'Houston': ('310xx', 'Houston', 'GA'),
 'Denali': ('997xx', 'Denali', 'AK'),
 'Valdez-Cordova': ('--', 'Valdez-Cordova', 'AK'),
 'Kenai Peninsula': ('996xx', 'Kenai Peninsula', 'AK'),
 'Yakutat': ('996xx', 'Yakutat', 'AK'),
 'Juneau': ('998xx', 'Juneau', 'AK'),
 'Lake and Peninsula': ('996xx', 'Lake and Peninsula', 'AK'),
 'Southeast Fairbanks': ('997xx', 'Southeast Fairbanks', 'AK'),
 'Yukon-Koyukuk': ('--', 'Yukon-Koyukuk', 'AK'),
 'Anchorage': ('995xx', 'Anchorage', 'AK'),
 'Aleutians East': ('995xx', 'Aleutians East', 'AK'),
 'Aleutians West': ('996xx', 'Aleutians West', 'AK'),
 'Bristol Bay': ('996xx', 'Bristol Bay', 'AK'),
 'Kodiak Island': ('996xx', 'Kodiak Island', 'AK'),
 'Northwest Arctic': ('997xx', 'Northwest Arctic', 'AK'),
 'Bethel': ('996xx', 'Bethel', 'AK'),
 'North Slope': ('997xx', 'North Slope', 'AK'),
 'Sitka': ('998xx', 'Sitka', 'AK'),
 'Fairbanks North Saintr': ('--', 'Fairbanks North Saintr', 'AK'),
 'Ketchikan Gateway': ('999xx', 'Ketchikan Gateway', 'AK'),
 'Matanuska-Susitna': ('--', 'Matanuska-Susitna', 'AK'),
 'Nome': ('996xx', 'Nome', 'AK'),
 'Dillingham': ('995xx', 'Dillingham', 'AK'),
 'Haines': ('998xx', 'Haines', 'AK'),
 'Prince of Wales-Hyder': ('--', 'Prince of Wales-Hyder', 'AK'),
 'Wrangell': ('998xx', 'Wrangell', 'AK'),
 'Hoonah-Angoon': ('--', 'Hoonah-Angoon', 'AK'),
 'Skagway': ('998xx', 'Skagway', 'AK'),
 'Petersburg': ('998xx', 'Petersburg', 'AK'),
 'Kusilvak': ('995xx', 'Kusilvak', 'AK'),
 'Pima': ('857xx', 'Pima', 'AZ'),
 'Maricopa': ('852xx', 'Maricopa', 'AZ'),
 'Gila': ('851xx', 'Gila', 'AZ'),
 'Yavapai': ('863xx', 'Yavapai', 'AZ'),
 'Yuma': ('807xx', 'Yuma', 'CO'),
 'Greenlee': ('859xx', 'Greenlee', 'AZ'),
 'Navajo': ('859xx', 'Navajo', 'AZ'),
 'Pinal': ('851xx', 'Pinal', 'AZ'),
 'Graham': ('855xx', 'Graham', 'AZ'),
 'Santa Cruz': ('950xx', 'Santa Cruz', 'CA'),
 'Cochise': ('856xx', 'Cochise', 'AZ'),
 'La Paz': ('853xx', 'La Paz', 'AZ'),
 'Mohave': ('864xx', 'Mohave', 'AZ'),
 'Apache': ('865xx', 'Apache', 'AZ'),
 'Coconino': ('860xx', 'Coconino', 'AZ'),
 'Union': ('320xx', 'Union', 'FL'),
 'Woodruff': ('720xx', 'Woodruff', 'AR'),
 'Pulaski': ('722xx', 'Pulaski', 'AR'),
 'White': ('720xx', 'White', 'AR'),
 'Lincoln': ('808xx', 'Lincoln', 'CO'),
 'Logan': ('807xx', 'Logan', 'CO'),
 'Ouachita': ('717xx', 'Ouachita', 'AR'),
 'Faulkner': ('721xx', 'Faulkner', 'AR'),
 'Howard': ('718xx', 'Howard', 'AR'),
 'Garland': ('719xx', 'Garland', 'AR'),
 'Mississippi': ('723xx', 'Mississippi', 'AR'),
 'Saline': ('721xx', 'Saline', 'AR'),
 'Van Buren': ('720xx', 'Van Buren', 'AR'),
 'Clark': ('719xx', 'Clark', 'AR'),
 'Bradley': ('716xx', 'Bradley', 'AR'),
 'Boone': ('726xx', 'Boone', 'AR'),
 'Izard': ('725xx', 'Izard', 'AR'),
 'Saint Francis': ('723xx', 'Saint Francis', 'AR'),
 'Fulton': ('300xx', 'Fulton', 'GA'),
 'Cross': ('723xx', 'Cross', 'AR'),
 'Drew': ('716xx', 'Drew', 'AR'),
 'Scott': ('729xx', 'Scott', 'AR'),
 'Independence': ('725xx', 'Independence', 'AR'),
 'Lafayette': ('320xx', 'Lafayette', 'FL'),
 'Phillips': ('807xx', 'Phillips', 'CO'),
 'Columbia': ('320xx', 'Columbia', 'FL'),
 'Saintne': ('--', 'Saintne', 'AR'),
 'Chicot': ('716xx', 'Chicot', 'AR'),
 'Hot Spring': ('719xx', 'Hot Spring', 'AR'),
 'Johnson': ('310xx', 'Johnson', 'GA'),
 'Polk': ('301xx', 'Polk', 'GA'),
 'Conway': ('720xx', 'Conway', 'AR'),
 'Newton': ('726xx', 'Newton', 'AR'),
 'Lonoke': ('720xx', 'Lonoke', 'AR'),
 'Carroll': ('726xx', 'Carroll', 'AR'),
 'Baxter': ('726xx', 'Baxter', 'AR'),
 'Ashley': ('716xx', 'Ashley', 'AR'),
 'Searcy': ('726xx', 'Searcy', 'AR'),
 'Cleveland': ('716xx', 'Cleveland', 'AR'),
 'Poinsett': ('724xx', 'Poinsett', 'AR'),
 'Nevada': ('959xx', 'Nevada', 'CA'),
 'Grant': ('721xx', 'Grant', 'AR'),
 'Crittenden': ('723xx', 'Crittenden', 'AR'),
 'Arkansas': ('721xx', 'Arkansas', 'AR'),
 'Little River': ('718xx', 'Little River', 'AR'),
 'Pope': ('728xx', 'Pope', 'AR'),
 'Prairie': ('721xx', 'Prairie', 'AR'),
 'Miller': ('398xx', 'Miller', 'GA'),
 'Craighead': ('724xx', 'Craighead', 'AR'),
 'Desha': ('716xx', 'Desha', 'AR'),
 'Sebastian': ('729xx', 'Sebastian', 'AR'),
 'Crawford': ('729xx', 'Crawford', 'AR'),
 'Hempstead': ('718xx', 'Hempstead', 'AR'),
 'Sharp': ('725xx', 'Sharp', 'AR'),
 'Benton': ('727xx', 'Benton', 'AR'),
 'Sevier': ('718xx', 'Sevier', 'AR'),
 'Yell': ('728xx', 'Yell', 'AR'),
 'Lake': ('347xx', 'Lake', 'FL'),
 'Mariposa': ('953xx', 'Mariposa', 'CA'),
 'Modoc': ('961xx', 'Modoc', 'CA'),
 'Yuba': ('959xx', 'Yuba', 'CA'),
 'Contra Costa': ('948xx', 'Contra Costa', 'CA'),
 'Inyo': ('935xx', 'Inyo', 'CA'),
 'Lassen': ('961xx', 'Lassen', 'CA'),
 'Saintnislaus': ('--', 'Saintnislaus', 'CA'),
 'Santa Barbara': ('930xx', 'Santa Barbara', 'CA'),
 'Sonoma': ('949xx', 'Sonoma', 'CA'),
 'Tehama': ('960xx', 'Tehama', 'CA'),
 'Imperial': ('922xx', 'Imperial', 'CA'),
 'Mono': ('935xx', 'Mono', 'CA'),
 'San Benito': ('950xx', 'San Benito', 'CA'),
 'Alameda': ('946xx', 'Alameda', 'CA'),
 'Sacramento': ('956xx', 'Sacramento', 'CA'),
 'El Dorado': ('956xx', 'El Dorado', 'CA'),
 'Napa': ('945xx', 'Napa', 'CA'),
 'Monterey': ('939xx', 'Monterey', 'CA'),
 'San Francisco': ('941xx', 'San Francisco', 'CA'),
 'Sierra': ('959xx', 'Sierra', 'CA'),
 'San Diego': ('920xx', 'San Diego', 'CA'),
 'Tulare': ('932xx', 'Tulare', 'CA'),
 'Yolo': ('959xx', 'Yolo', 'CA'),
 'Humboldt': ('955xx', 'Humboldt', 'CA'),
 'Alpine': ('956xx', 'Alpine', 'CA'),
 'Madera': ('936xx', 'Madera', 'CA'),
 'Mendocino': ('954xx', 'Mendocino', 'CA'),
 'Trinity': ('955xx', 'Trinity', 'CA'),
 'Los Angeles': ('913xx', 'Los Angeles', 'CA'),
 'Riverside': ('925xx', 'Riverside', 'CA'),
 'San Bernardino': ('923xx', 'San Bernardino', 'CA'),
 'Santa Clara': ('940xx', 'Santa Clara', 'CA'),
 'Marin': ('949xx', 'Marin', 'CA'),
 'Placer': ('956xx', 'Placer', 'CA'),
 'Siskiyou': ('960xx', 'Siskiyou', 'CA'),
 'Shasta': ('960xx', 'Shasta', 'CA'),
 'Solano': ('945xx', 'Solano', 'CA'),
 'Del Norte': ('955xx', 'Del Norte', 'CA'),
 'Colusa': ('959xx', 'Colusa', 'CA'),
 'Glenn': ('959xx', 'Glenn', 'CA'),
 'Butte': ('959xx', 'Butte', 'CA'),
 'Calaveras': ('952xx', 'Calaveras', 'CA'),
 'Kings': ('932xx', 'Kings', 'CA'),
 'Plumas': ('961xx', 'Plumas', 'CA'),
 'San Luis Obispo': ('934xx', 'San Luis Obispo', 'CA'),
 'Fresno': ('936xx', 'Fresno', 'CA'),
 'Kern': ('935xx', 'Kern', 'CA'),
 'Orange': ('328xx', 'Orange', 'FL'),
 'Ventura': ('913xx', 'Ventura', 'CA'),
 'Sutter': ('959xx', 'Sutter', 'CA'),
 'San Mateo': ('943xx', 'San Mateo', 'CA'),
 'Tuolumne': ('953xx', 'Tuolumne', 'CA'),
 'San Joaquin': ('952xx', 'San Joaquin', 'CA'),
 'Amador': ('956xx', 'Amador', 'CA'),
 'Merced': ('953xx', 'Merced', 'CA'),
 'Archuleta': ('811xx', 'Archuleta', 'CO'),
 'Denver': ('802xx', 'Denver', 'CO'),
 'Kiowa': ('810xx', 'Kiowa', 'CO'),
 'Huerfano': ('810xx', 'Huerfano', 'CO'),
 'Baca': ('810xx', 'Baca', 'CO'),
 'Chaffee': ('812xx', 'Chaffee', 'CO'),
 'Gilpin': ('804xx', 'Gilpin', 'CO'),
 'Kit Carson': ('808xx', 'Kit Carson', 'CO'),
 'Garfield': ('816xx', 'Garfield', 'CO'),
 'Gunnison': ('812xx', 'Gunnison', 'CO'),
 'Mineral': ('811xx', 'Mineral', 'CO'),
 'Ouray': ('814xx', 'Ouray', 'CO'),
 'Rio Blanco': ('816xx', 'Rio Blanco', 'CO'),
 'Sedgwick': ('807xx', 'Sedgwick', 'CO'),
 'Weld': ('805xx', 'Weld', 'CO'),
 'Conejos': ('811xx', 'Conejos', 'CO'),
 'Custer': ('812xx', 'Custer', 'CO'),
 'Costilla': ('811xx', 'Costilla', 'CO'),
 'Adams': ('802xx', 'Adams', 'CO'),
 'Douglas': ('301xx', 'Douglas', 'GA'),
 'Eagle': ('816xx', 'Eagle', 'CO'),
 'La Plata': ('813xx', 'La Plata', 'CO'),
 'Moffat': ('816xx', 'Moffat', 'CO'),
 'Pitkin': ('816xx', 'Pitkin', 'CO'),
 'Rio Grande': ('811xx', 'Rio Grande', 'CO'),
 'Cheyenne': ('808xx', 'Cheyenne', 'CO'),
 'Bent': ('810xx', 'Bent', 'CO'),
 'Crowley': ('810xx', 'Crowley', 'CO'),
 'Dolores': ('813xx', 'Dolores', 'CO'),
 'San Juan': ('814xx', 'San Juan', 'CO'),
 'Larimer': ('805xx', 'Larimer', 'CO'),
 'Montezuma': ('813xx', 'Montezuma', 'CO'),
 'San Miguel': ('814xx', 'San Miguel', 'CO'),
 'Teller': ('808xx', 'Teller', 'CO'),
 'Boulder': ('805xx', 'Boulder', 'CO'),
 'Elbert': ('808xx', 'Elbert', 'CO'),
 'Las Animas': ('810xx', 'Las Animas', 'CO'),
 'Routt': ('804xx', 'Routt', 'CO'),
 'Summit': ('804xx', 'Summit', 'CO'),
 'Alamosa': ('811xx', 'Alamosa', 'CO'),
 'Clear Creek': ('804xx', 'Clear Creek', 'CO'),
 'Delta': ('814xx', 'Delta', 'CO'),
 'Fremont': ('812xx', 'Fremont', 'CO'),
 'Pueblo': ('810xx', 'Pueblo', 'CO'),
 'Montrose': ('814xx', 'Montrose', 'CO'),
 'Park': ('808xx', 'Park', 'CO'),
 'Saguache': ('811xx', 'Saguache', 'CO'),
 'Mesa': ('815xx', 'Mesa', 'CO'),
 'Prowers': ('810xx', 'Prowers', 'CO'),
 'Hinsdale': ('812xx', 'Hinsdale', 'CO'),
 'El Paso': ('809xx', 'El Paso', 'CO'),
 'Grand': ('804xx', 'Grand', 'CO'),
 'Arapahoe': ('801xx', 'Arapahoe', 'CO'),
 'Otero': ('810xx', 'Otero', 'CO'),
 'Broomfield': ('800xx', 'Broomfield', 'CO'),
 'Middlesex': ('064xx', 'Middlesex', 'CT'),
 'Hartford': ('060xx', 'Hartford', 'CT'),
 'Windham': ('062xx', 'Windham', 'CT'),
 'Tolland': ('060xx', 'Tolland', 'CT'),
 'Fairfield': ('069xx', 'Fairfield', 'CT'),
 'New Haven': ('067xx', 'New Haven', 'CT'),
 'Litchfield': ('060xx', 'Litchfield', 'CT'),
 'New London': ('063xx', 'New London', 'CT'),
 'District of Columbia': ('204xx', 'District of Columbia', 'DC'),
 'New Castle': ('197xx', 'New Castle', 'DE'),
 'Sussex': ('199xx', 'Sussex', 'DE'),
 'Kent': ('199xx', 'Kent', 'DE'),
 'Pasco': ('335xx', 'Pasco', 'FL'),
 'Gilchrist': ('326xx', 'Gilchrist', 'FL'),
 'Highlands': ('338xx', 'Highlands', 'FL'),
 'Suwannee': ('320xx', 'Suwannee', 'FL'),
 'Alachua': ('326xx', 'Alachua', 'FL'),
 'DeSoto': ('342xx', 'DeSoto', 'FL'),
 'Charlotte': ('339xx', 'Charlotte', 'FL'),
 'Dixie': ('326xx', 'Dixie', 'FL'),
 'Martin': ('334xx', 'Martin', 'FL'),
 'Putnam': ('321xx', 'Putnam', 'FL'),
 'Sarasota': ('342xx', 'Sarasota', 'FL'),
 'Okaloosa': ('325xx', 'Okaloosa', 'FL'),
 'Taylor': ('310xx', 'Taylor', 'GA'),
 'Wakulla': ('323xx', 'Wakulla', 'FL'),
 'Duval': ('322xx', 'Duval', 'FL'),
 'Bradford': ('320xx', 'Bradford', 'FL'),
 'Brevard': ('329xx', 'Brevard', 'FL'),
 'Nassau': ('320xx', 'Nassau', 'FL'),
 'Pinellas': ('337xx', 'Pinellas', 'FL'),
 'Saint Lucie': ('349xx', 'Saint Lucie', 'FL'),
 'Glades': ('334xx', 'Glades', 'FL'),
 'Hendry': ('334xx', 'Hendry', 'FL'),
 'Indian River': ('329xx', 'Indian River', 'FL'),
 'Palm Beach': ('334xx', 'Palm Beach', 'FL'),
 'Saint Johns': ('320xx', 'Saint Johns', 'FL'),
 'Seminole': ('398xx', 'Seminole', 'GA'),
 'Miami-Dade': ('331xx', 'Miami-Dade', 'FL'),
 'Bay': ('324xx', 'Bay', 'FL'),
 'Flagler': ('321xx', 'Flagler', 'FL'),
 'Gulf': ('324xx', 'Gulf', 'FL'),
 'Hamilton': ('320xx', 'Hamilton', 'FL'),
 'Liberty': ('313xx', 'Liberty', 'GA'),
 'Osceola': ('347xx', 'Osceola', 'FL'),
 'Walton': ('324xx', 'Walton', 'FL'),
 'Gadsden': ('323xx', 'Gadsden', 'FL'),
 'Holmes': ('324xx', 'Holmes', 'FL'),
 'Hardee': ('338xx', 'Hardee', 'FL'),
 'Collier': ('341xx', 'Collier', 'FL'),
 'Okeechobee': ('349xx', 'Okeechobee', 'FL'),
 'Baker': ('320xx', 'Baker', 'FL'),
 'Santa Rosa': ('325xx', 'Santa Rosa', 'FL'),
 'Volusia': ('327xx', 'Volusia', 'FL'),
 'Leon': ('323xx', 'Leon', 'FL'),
 'Broward': ('330xx', 'Broward', 'FL'),
 'Hernando': ('346xx', 'Hernando', 'FL'),
 'Hillsborough': ('336xx', 'Hillsborough', 'FL'),
 'Manatee': ('342xx', 'Manatee', 'FL'),
 'Citrus': ('344xx', 'Citrus', 'FL'),
 'Levy': ('326xx', 'Levy', 'FL'),
 'Bleckley': ('310xx', 'Bleckley', 'GA'),
 'Dooly': ('310xx', 'Dooly', 'GA'),
 'Evans': ('304xx', 'Evans', 'GA'),
 'Webster': ('318xx', 'Webster', 'GA'),
 'Effingham': ('313xx', 'Effingham', 'GA'),
 'Glascock': ('308xx', 'Glascock', 'GA'),
 'Emanuel': ('304xx', 'Emanuel', 'GA'),
 'Quitman': ('398xx', 'Quitman', 'GA'),
 'Twiggs': ('310xx', 'Twiggs', 'GA'),
 'Talbot': ('318xx', 'Talbot', 'GA'),
 'Grady': ('398xx', 'Grady', 'GA'),
 'Jeff Davis': ('315xx', 'Jeff Davis', 'GA'),
 'Oglethorpe': ('306xx', 'Oglethorpe', 'GA'),
 'Rockdale': ('300xx', 'Rockdale', 'GA'),
 'Ware': ('315xx', 'Ware', 'GA'),
 'Wayne': ('315xx', 'Wayne', 'GA'),
 'Wheeler': ('304xx', 'Wheeler', 'GA'),
 'Terrell': ('398xx', 'Terrell', 'GA'),
 'Thomas': ('317xx', 'Thomas', 'GA'),
 'Toombs': ('304xx', 'Toombs', 'GA'),
 'Wilkinson': ('310xx', 'Wilkinson', 'GA'),
 'Whitfield': ('307xx', 'Whitfield', 'GA'),
 'Troup': ('302xx', 'Troup', 'GA'),
 'Harris': ('318xx', 'Harris', 'GA'),
 'Schley': ('318xx', 'Schley', 'GA'),
 'Worth': ('317xx', 'Worth', 'GA'),
 'Chatham': ('314xx', 'Chatham', 'GA'),
 'Jasper': ('300xx', 'Jasper', 'GA'),
 'Lanier': ('316xx', 'Lanier', 'GA'),
 'Mitchell': ('317xx', 'Mitchell', 'GA'),
 'Tift': ('317xx', 'Tift', 'GA'),
 'Hall': ('305xx', 'Hall', 'GA'),
 'Hancock': ('310xx', 'Hancock', 'GA'),
 'Lumpkin': ('305xx', 'Lumpkin', 'GA'),
 'McDuffie': ('308xx', 'McDuffie', 'GA'),
 'Heard': ('302xx', 'Heard', 'GA'),
 'Oconee': ('306xx', 'Oconee', 'GA'),
 'Dougherty': ('317xx', 'Dougherty', 'GA'),
 'Fannin': ('305xx', 'Fannin', 'GA'),
 'Laurens': ('310xx', 'Laurens', 'GA'),
 'Long': ('313xx', 'Long', 'GA'),
 'Spalding': ('302xx', 'Spalding', 'GA'),
 'Saintphens': ('--', 'Saintphens', 'GA'),
 'Banks': ('305xx', 'Banks', 'GA'),
 'Bulloch': ('304xx', 'Bulloch', 'GA'),
 'Echols': ('316xx', 'Echols', 'GA'),
 'Glynn': ('315xx', 'Glynn', 'GA'),
 'Haralson': ('301xx', 'Haralson', 'GA')}

 index:459   county_name: Haralson   state: GA
('301xx', 'Haralson', 'GA')

